config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :menus
  resources :categories

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_categories
  has_many :categories, through: :menu_categories
  has_many :order_details

  validates :name, presence: true, uniqueness: {case_sensitive: false}
  validates :price, presence: true, numericality: true, comparison: { greater_than_or_equal_to: 0.01 }
  validates :description, length: {maximum: 150}

  validate :has_one_category_at_least

  def has_one_category_at_least
    if menu_categories.empty?
      errors.add(:menu_categories, "need one category at least")
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: %i[ show edit update destroy ]

  # GET /menus or /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1 or /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus or /menus.json
  def create
    @menu = helpers.add_menu_with_categories(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully created." }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1 or /menus/1.json
  def update
    @menu = helpers.update_menu_with_category(menu_params, @menu)
    respond_to do |format|
      if @menu.save
        format.html { redirect_to menu_url(@menu), notice: "Menu was successfully updated." }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1 or /menus/1.json
  def destroy
    @menu.menu_categories.destroy_all
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url, notice: "Menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:name, :description, :price, category_ids: [])
    end
end

app/helpers/menus_helper.rb
module MenusHelper
  def add_menu_with_categories(attributes)
    menu = Menu.new(name: attributes[:name], description: attributes[:description], price: attributes[:price])
    category_ids = attributes[:category_ids]
    categories = []
    category_ids.each do |category_id|
      categories << Category.find(category_id)
    end
    categories.each do |category|
      menu.menu_categories << MenuCategory.create(category: category)
    end
    menu
  end

  def update_menu_with_category(attributes, menu)
    menu.menu_categories.destroy_all
    menu.update(name: attributes[:name], description: attributes[:description], price: attributes[:price])
    category_ids = attributes[:category_ids]
    categories = []
    category_ids.each do |category_id|
      categories << Category.find(category_id)
    end
    categories.each do |category|
      menu.menu_categories << MenuCategory.create(category: category)
    end
    menu
  end
end

app/views/menus/_form.html.erb
<%= form_with(model: menu) do |form| %>
  <% if menu.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
        <% menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <% Category.all.each do |category| %>
      <%=  check_box_tag "menu[category_ids][]", category.id  %>
      <%= h category.name  %><br/>
    <% end%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/_menu.html.erb
<div id="<%= dom_id menu %>">
  <p>
    <strong>Name:</strong>
    <%= menu.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= menu.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= menu.price %>
  </p>

</div>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Show this menu", @menu %> |
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Menus</h1>

<div id="menus">
  <% @menus.each do |menu| %>
    <%= render menu %>
    <p>
      <%= link_to "Show this menu", menu %>
    </p>
  <% end %>
</div>

<%= link_to "New menu", new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render "form", menu: @menu %>

<br>

<div>
  <%= link_to "Back to menus", menus_path %>
</div>

app/views/menus/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu %>

<div>
  <%= link_to "Edit this menu", edit_menu_path(@menu) %> |
  <%= link_to "Back to menus", menus_path %>

  <%= button_to "Destroy this menu", @menu, method: :delete %>
</div>