config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :menus
  resources :categories

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :order_details
  has_many :order_details, class_name: "OrderDetail"

  validates :email, presence: true,
            format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: "invalid email"}

  accepts_nested_attributes_for :order_details, allow_destroy: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @order_details = OrderDetail.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:email, :status, :total)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.text_field :total %>
  </div>

  <div>
    <%= form.fields_for :OrderDetail do |builder| %>
      <%= render 'order_detail_fields', f: builder %>
      <%= link_to "[add]",class_names: "add_fields" %>
    <%end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
<script>
    $('.remove_fields').click(function () {
        $(this).prev('input[type=hidden]').val('1')
        $(this).closest('fieldset').hide()
        this.preventDefault()
    })
    $('.add_fields').click(function () {
        time = new Date().getTime()
        regexp = new RegExp($(this).data('id'), 'g')
        $(this).before($(this).data('fields').replace(regexp, time))
        this.preventDefault()
    })
</script>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Email:</strong>
    <%= order.email %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= order.total %>
  </p>

</div>

app/views/orders/_order_detail_fields.html.erb
<fieldset>
  <% f.select :field_type, %w[collection_select, number_field]%>
  <%= f.collection_select :menu_id, Menu.all, :id, :name, include_blank: true %>
  <%= f.number_field :quantity %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "[remove]", class: "remove_fields" %>
</fieldset>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
  <% @orders.each do |order| %>
    <%= render order %>
    <p>
      <%= link_to "Show this order", order %>
    </p>
  <% end %>
</div>

<%= link_to "New order", new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>